# Generated by Django 4.0.4 on 2022-04-29 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0001_remove_postmodel_author_remove_postmodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=210, verbose_name='sub-titulo'),
        ),
    ]
