# Generated by Django 4.0.4 on 2022-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_postmodel_author_alter_postmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='datePublish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
