# Generated by Django 4.0.4 on 2022-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_alter_postmodel_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criar_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='publicacao',
        ),
    ]
