# Generated by Django 4.0.4 on 2022-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_criar_categoria_remove_postmodel_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='categories',
            field=models.ManyToManyField(to='post_app.criar_categoria'),
        ),
    ]
