# Generated by Django 4.0.4 on 2022-05-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0012_categorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryModel',
        ),
    ]
