# Generated by Django 4.0.4 on 2022-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_postmodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.BooleanField(default=1, verbose_name=(('draft', 'Draft'), ('published', 'Published'))),
            preserve_default=False,
        ),
    ]
