# Generated by Django 4.0.4 on 2022-05-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0016_postmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='status',
        ),
    ]
