# Generated by Django 4.0.4 on 2022-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0018_post_remove_postmodel_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTitle', models.CharField(max_length=250, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
