# Generated by Django 4.0.4 on 2022-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categ',
            field=models.ManyToManyField(to='post_app.category'),
        ),
    ]
